version: '3.9'

services:
  db:
    image: postgis/postgis
    container_name: pg_trips
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trips_db
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: fastapi_trips
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    working_dir: /code
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
